#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=ass2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=02:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1

# Your job starts in the directory where you call sbatch
cd $HOME/AI_for_medical_imaging_course/Assignment\ 2
# Activate your environment
source /gpfs/work5/0/prjs1312/venv/bin/activate
# Run your code
srun python -u main_CNN.py --max_epochs 100 --optimizer_name adam --optimizer_lr 0.0001 --batch_size 64 --experiment_name test_cnn02 --model_name transfer_convent