#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --job-name=ExampleJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=00:50:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1 

# Your job starts in the directory where you call sbatch
#cd $HOME/...
# Activate your environment
#source /projects/0/gpuuva035/venv3/bin/activate
#source ../venv3/bin/activate
echo $VIRTUAL_ENV
# Run your code
python train_VarNet.py --experiment_name "Snellius run Varnet"


