#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --job-name=ExampleJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load PyTorch/1.12.0-foss-2022a-CUDA-11.7.0

# Your job starts in the directory where you call sbatch
cd $HOME/Exercise_2
# Activate your environment
source /projects/0/gpuuva035/venv/bin/activate
# Run your code
srun python -u main_UNET.py